return {
  { import = "plugins.ui.highlight-colors" },
--  { import = "plugins.ui.illuminate" },
  { import = "plugins.ui.lualine" },
--  { import = "plugins.ui.markdown-preview" },
  { import = "plugins.ui.mini-base16" },
  { import = "plugins.ui.neo-tree" },
  { import = "plugins.ui.notifications" },
--  { import = "plugins.ui.nvim-numbertoggle" },
  { import = "plugins.ui.range-highlight" },
  { import = "plugins.ui.snacks" },
  { import = "plugins.ui.trouble" },
  { import = "plugins.ui.ufo" },
  { import = "plugins.ui.vimade" },
  { import = "plugins.ui.which-key" },
  { import = "plugins.ui.zen-mode" },
}
